### ISSUE TITLE
Problem with datasets

### ISSUE THREAD

**Issue by KevinMeng49** [CharlotteMagister/GCExplainer#3]
I am wondering how to get the datasets like BA_shapes and BA_Houses
Cause in the function "load_syn_data",I can't find path "../../data/BA_Community/graph_ba_350_100_2comm.gpickel"

**Comment by CharlotteMagister** [comment]
Hi, I did not upload the datasets to keep the repo size small. The graph classification datasets are part of the benchmark dataset for graph kernels released by TU Dortmund [here](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets).  The node classification datasets can be generated using the code provided for [GNNExplainer](https://proceedings.neurips.cc/paper/2019/file/d80b7040b773199015de6d3b4293c8ff-Paper.pdf) [here](https://github.com/RexYing/gnn-model-explainer).

Let me know if you have any other questions. Thank you for your time and patience!
